version: '3.7'

services:
  tor:
    image: ${CORE_TOR_DOCKER_IMAGE:?err}
    restart: unless-stopped
    ports:
      - ${CORE_TOR_PROXY_PORT:?err}:${CORE_TOR_PROXY_PORT:?err}
    volumes:
      - ${DASHMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/core/tor/torrc:/etc/tor/torrc
    environment:
      - PASSWORD=${CORE_TOR_CONTROL_PASSWORD}

  core:
    image: ${CORE_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - tor
    ports:
      - ${CORE_P2P_PORT:?err}:${CORE_P2P_PORT:?err} # P2P
      - 127.0.0.1:${CORE_RPC_PORT:?err}:${CORE_RPC_PORT:?err} #RPC
    volumes:
      - core_data:/dash
      - ${DASHMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/core/dash.conf:/dash/.dashcore/dash.conf
    environment:
      - TOR_CONTROL_HOST=tor
      - TOR_CONTROL_PORT=${CORE_TOR_CONTROL_PORT}
      - TOR_CONTROL_PASSWORD=${CORE_TOR_CONTROL_PASSWORD}
      - TOR_PROXY_PORT=${CORE_TOR_PROXY_PORT}
    command:
      - dashd
      - -masternodeblsprivkey=${CORE_MASTERNODE_OPERATOR_PRIVATE_KEY}

  sentinel:
    image: ${CORE_SENTINEL_DOCKER_IMAGE:?err}
    restart: unless-stopped
    depends_on:
      - core
    environment:
      - DEBUG=false
      - RPCUSER=${CORE_RPC_USER:?err}
      - RPCPASSWORD=${CORE_RPC_PASSWORD:?err}
      - RPCHOST=core
      - RPCPORT=${CORE_RPC_PORT:?err}
      - NETWORK=${NETWORK?:err}
      - SENTINEL_ARGS=-b

volumes:
  core_data:
