version: '3.7'

services:
  core_tor:
    image: ${CORE_TOR_DOCKER_IMAGE:?err}
    restart: unless-stopped
    ports:
      - ${CORE_TOR_PROXY_PORT:?err}:${CORE_TOR_PROXY_PORT:?err}
    volumes:
      - ${DASHMATE_HOME_DIR:?err}/${CONFIG_NAME:?err}/core/tor/torrc:/etc/tor/torrc
    environment:
      - SERVICE=${CORE_P2P_PORT:?err};core:${CORE_P2P_PORT:?err}
